### ISSUE TITLE
Rendering process failed

### ISSUE THREAD

**Issue by nalecu** [GetPublii/theme-Blank#1]
Hello, I was trying to experiment with the Blank theme and I got this error:
Rendering process failed
An error (1002) occurred during parsing index.hbs file.
Missing helper: "lazyload"

I'm guessing this is a theme specific issue, because all other themes I tried work perfectly fine.
I should also mention that I'm a total noob when it comes to Publii, I very much like it so far but I'm not yet familiar with it's inner workings.

**Comment by GetPublii** [comment]
This theme is compatible and only works with Publii 36 Prerelease 5. https://getpublii.com/forum/topic/publii-0-36-prerelease-5/

**Comment by nalecu** [comment]
OK, I missed that, thank you!
One more question, though: is the older Starter theme compatible with v.0.35.3?

**Comment by enzofoucaud** [comment]
> This theme is compatible and only works with Publii 36 Prerelease 5. https://getpublii.com/forum/topic/publii-0-36-prerelease-5/

Publii 0.38.3 (build 14239) works ? because I have the same error
