### ISSUE TITLE
Render failed: wrong script filename

### ISSUE THREAD

**Issue by rjcpereira** [GetPublii/theme-Blank#2]
Rendering process failed because the script file in footer partial template has a wrong name
file name: **script.js**
required file: `<script async src="{{js "scripts.js"}}"></script>`

**Comment by spsrinivas** [comment]
<img width="598" alt="Screenshot 2020-05-10 at 12 11 13 AM" src="https://user-images.githubusercontent.com/8235909/81478901-c519d700-9252-11ea-9d75-1c33b7f462cd.png">

This happens in dark theme

**Comment by bobmitro** [comment]
What do you mean by  dark theme? 
What Publii version do you use? The blank theme works only with the 0.36 version https://getpublii.com/forum/topic/publii-0-36-prerelease-5/
