### ISSUE TITLE
lazyload error in Blank theme when attempting to preview

### ISSUE THREAD

**Issue by leepenney** [GetPublii/theme-Blank#5]
I downloaded the Blank theme, added to Publii (v0.35.3 (build 12104)) and attempted to preview a very simple site, but received the following error:

`Rendering process failed
An error (1002) occurred during parsing index.hbs file.

Missing helper: "lazyload"`

**Comment by bobmitro** [comment]
What version of Publii are you using? In order to work properly, the Blank theme requires at least 0.36 version.

**Comment by leepenney** [comment]
0.35.3 (as mentioned). Switching to 0.36.1 did indeed fix it.

Might be worth an extra option in the config.json file that lets you specify the minimum version of Publii that it can be used on and to check this before allowing it to be added.

Hell, noting it somewhere in the documentation would be a start.
